### ISSUE TITLE
Extend functionality with cloze-style flashcard generation

### ISSUE THREAD

**Issue by paulbricman** [paulbricman/autocards#3]
> It would also be amazing if it could generate cloze deletions

Tentative answers can directly get translated into cloze-style flashcards.

**Comment by bjsi** [comment]
Managed to do this on my fork [here](https://github.com/bjsi/Autocards). Would be happy to commit this back into the main version and add support for both SuperMemo and Anki style clozes. Interestingly, cloze generation is way faster than Q/A generation because you don't need to do the additional question generation step!

**Comment by paulbricman** [comment]
Awesome! I'd be happy to review an eventual PR and give it a try before merging @bjsi . :eyes:

**Comment by thiswillbeyourgithub** [comment]
This has been implemented so closing.
